## Loconotion Site Configuration File ##
# full .toml configuration example file to showcase all of Loconotion's available settings
# check out https://github.com/toml-lang/toml for more info on the toml format

# name of the folder that the site will be generated in
name = "AgenteLab"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://agente.notion.site/Agente-Org-Design-1118e6db68274fbfba357aac11070e4b"

# optionally apply notion's dark mode, remove the line below to use the default light mode
theme = "light"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "Agente Lab"
  content = "Loconotion Test Site"
  [[site.meta]]
  name = "description"
  content = "Design Organizacional, Design de comunidades: acompanhamento e facilitação"

  ## Custom Fonts ##
  # you can specify the name of a google font to use on the site - use the font embed name
  # if in doubt select a style on fonts.google.com and navigate to the "embed" tag to
  # check the name under CSS rules
  # the following table keys controls the font of specific elements:
  #   site: changes the font for the whole page (apart from code blocks)
  #         but the settings below override it
  #   navbar: site breadcrumbs on the top-left of the page
  #   title: page title (under the icon)
  #   h1: heading blocks, and inline databases' titles
  #   h2: sub-heading blocks
  #   h3: sub-sub-heading blocks
  #   body: non-heading text on the page
  #   code: text inside code blocks
  [site.fonts]
  site = 'Inter'
  navbar = 'Inter'
  title = 'Inter'
  h1 = 'Inter'
  h2 = 'Inter'
  h3 = 'Inter'
  body = 'Roboto'
  code = 'Inconsolata'

  ## Custom Element Injection ##
  # defined as an array of tables [[site.inject]], followed by 'head' or 'body' to set
  # the injection point, followed by name of the tag to inject
  # each key in the table maps to an atttribute in the tag
  # e.g. the following injects this tag in the <head>:
  #   <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  [[site.inject.head.link]]
  rel="icon"
  sizes="16x16"
  type="image/png"
  href="/site/favicon-16x16.png"

  [[site.inject.head.link]]
  rel="icon"
  sizes="32x32"
  type="image/png"
  href="/site/favicon-32x32.png"

  [[site.inject.head.link]]
  rel="stylesheet"
  type="text/css"
  href="/site/styles.css"

  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder
  # regardless of their original path
  # [[site.inject.body.script]]
  # type="text/javascript"
  # src="/site/custom-script.js"


## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  [pages.10a7bbb5d834ea4bb531f9e49e9febb]
    slug = "desenhar-sua-organisacao"

  [pages.ef079058b4034e709d47b457f179e9f3]
    slug = "organisacao-interna"

  [pages.d7923795dfa64069aa515de5e56f432e]
    slug = "comunidades"
    no-links = true

  [pages.7b91094b1a364361adc6572772532678]
    slug = "polly"
    no-links = true

  [pages.216e6441158144efa3ec2b8a5b905dd9]
    slug = "kad"
    no-links = true

  [pages.510bddef42a6488682653ca3a5973550]
    slug = "rodrigo"
    no-links = true

  [pages.5f92c0a4d2d749299c96a0358738cf61]
    slug = "gabriela"
    no-links = true

  [pages.896296d9564145898037877469068623]
    slug = "cosmotecnicas-amazonicas"
    no-links = true

  [pages.722849e514164076b4806a0cd18bb1a6]
    slug = "internal"
    no-links = true

